### ISSUE TITLE
Cannot get ScheduleTask configuration

### ISSUE THREAD

**Issue by spawluk** [guitarrapc/GraniResource#62]
I've wrote resource for scheduled task:

```
cScheduleTask {Name} #ResourceName
    {
      Ensure                           = "Present"
      TaskName                         = "TaskName"
      Credential                       = $credential
      Execute                          = "{execute}"
      TaskPath                         = "\"
      ScheduledAt                      = @([DateTime]"00:00:00")
      RepetitionIntervalTimeSpanString = @([TimeSpan]::FromMinutes(10).ToString())
      RepetitionDurationTimeSpanString = @([TimeSpan]::MaxValue.ToString())
      Disable                          = $false
      Hidden                           = $false
      WorkingDirectory                 = "{workingDirectory}"
    }
```

Resource can be created but when I try `Get-DscConfiguration` I get:

```
Get-DscConfiguration : GetConfiguration did not succeed.
At line:1 char:1
+ Get-DscConfiguration -CimSession {name} -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get-DscConfiguration], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Get-DscConfiguration
    + PSComputerName        : {name}
```

I also get ERROR in ETW:

```
Message Unable to cast object of type 'System.String' to type 'System.Collections.IList'.
Parameter name: value 
HResult -2147024809 
StackTrack    at Microsoft.Management.Infrastructure.Internal.Data.CimPropertyOfInstance.set_Value(Object value)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamsHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)
```

**Comment by guitarrapc** [comment]
It seems like bug. I will check it.

**Comment by guitarrapc** [comment]
Issue relates to ```RepetitionIntervalTimeSpanString```

**Comment by guitarrapc** [comment]
Fixed.

https://github.com/guitarrapc/GraniResource/commit/eefab3d98c9cf7590fef1e18f671992ffc8b1009
